export const SANTA_FE_LOCALIDADES: string[] = [
  "Aarón Castellanos",
  "Acébal",
  "Aguará Grande",
  "Albarellos",
  "Alcorta",
  "Aldao",
  "Alejandra",
  "Álvarez",
  "Alvear",
  "Ambrosetti",
  "Amenábar",
  "Angel Gallardo",
  "Angélica",
  "Angeloni",
  "Arbilla",
  "Arequito",
  "Arminda",
  "Armstrong",
  "Arocena",
  "Arroyo Aguiar",
  "Arroyo Ceibal",
  "Arroyo Leyes",
  "Arroyo Seco",
  "Arrufo",
  "Arteaga",
  "Ataliva",
  "Aurelia",
  "Avellaneda",
  "Balneario La Verde",
  "Balneario Monje",
  "Barrancas",
  "Barrio Arroyo del Medio",
  "Barrio Caima",
  "Barrio Cicarelli",
  "Barrio El Pacaá - Barrio Comipini",
  "Barrio Mitre",
  "Barrios Acapulco y Veracruz",
  "Bauer y Sigel",
  "Bella Italia",
  "Beravebú",
  "Berna",
  "Bernardo de Irigoyen",
  "Bigand",
  "Bombal",
  "Bouquet",
  "Bustinza",
  "Cabal",
  "Cacique Ariacaiquín",
  "Cafferata",
  "Calchaquí",
  "Campo Andino",
  "Candioti",
  "Cañada de Gómez",
  "Cañada del Ucle",
  "Cañada Ombú",
  "Cañada Rica",
  "Cañada Rosquín",
  "Capitán Bermúdez",
  "Capivara",
  "Carcarañá",
  "Carlos Pellegrini",
  "Carmen",
  "Carmen del Sauce",
  "Carreras",
  "Carrizales",
  "Casalegno",
  "Casas",
  "Casilda",
  "Castelar",
  "Castellanos",
  "Cavour",
  "Cayastá",
  "Cayastacito",
  "Centeno",
  "Cepeda",
  "Ceres",
  "Chabas",
  "Chañar Ladeado",
  "Chapuy",
  "Chovet",
  "Christophersen",
  "Classon",
  "Colmena",
  "Colonia Ana",
  "Colonia Belgrano",
  "Colonia Bicha",
  "Colonia Bossi",
  "Colonia Cello",
  "Colonia Dolores",
  "Colonia Durán",
  "Colonia Margarita",
  "Colonia Médici",
  "Colonia Raquel",
  "Colonia Rosa",
  "Constanza",
  "Coronda",
  "Coronel Arnold",
  "Coronel Bogado",
  "Coronel Fraga",
  "Coronel Rodolfo S. Domínguez",
  "Correa",
  "Crispi",
  "Cuatro Esquinas",
  "Cululú",
  "Curupaytí",
  "Desvío Arijón",
  "Díaz",
  "Diego de Alvear",
  "Egusquiza",
  "El Araza",
  "El Caramelo",
  "El Rabón",
  "El Trébol",
  "Elisa",
  "Elortondo",
  "Emilia",
  "Empalme San Carlos",
  "Empalme Villa Constitución",
  "Esmeralda",
  "Esperanza",
  "Estación Clucellas",
  "Estación Presidente Roca",
  "Estación Saguier",
  "Esteban Rams",
  "Esther",
  "Eusebia y Carolina",
  "Eustolia",
  "Felicia",
  "Fighiera",
  "Firmat",
  "Florencia",
  "Fortín Olmos",
  "Franck",
  "Fray Luis Beltrán",
  "Frontera",
  "Fuentes",
  "Funes",
  "Gaboto",
  "Gálvez",
  "Garabato",
  "Garibaldi",
  "Gato Colorado",
  "General Gelly",
  "General Lagos",
  "Gessler",
  "Gobernador Crespo",
  "Gödeken",
  "Godoy",
  "Golondrina",
  "Granadero Baigorria",
  "Gregoria Pérez de Denis",
  "Grutly",
  "Guadalupe Norte",
  "Helvecia",
  "Hersilia",
  "Hipatía",
  "Huanqueros",
  "Hughes",
  "Humberto Primo",
  "Humboldt",
  "Ibarlucea",
  "Ingeniero Chanourdie",
  "Intiyaco",
  "Irigoyen",
  "Jacinto L. Aráuz",
  "Josefina",
  "Juan B. Molina",
  "Juncal",
  "Kilómetro 101",
  "Kilómetro 115",
  "La Brava",
  "La Cabral",
  "La Chispa",
  "La Criolla",
  "La Gallareta",
  "La Isleta",
  "La Lucila",
  "La Pelada",
  "La Penca y Caraguatá",
  "La Rubia",
  "La Sarita",
  "La Vanguardia",
  "Labordeboy",
  "Laguna Paiva",
  "Landeta",
  "Lanteri",
  "Larguía",
  "Larrechea",
  "Las Avispas",
  "Las Bandurrias",
  "Las Garzas",
  "Las Palmeras",
  "Las Parejas",
  "Las Petacas",
  "Las Rosas",
  "Las Toscas",
  "Las Tunas",
  "Lazzarino",
  "Lehmann",
  "Llambi Campbell",
  "Logroño",
  "Loma Alta",
  "López",
  "Los Amores",
  "Los Cardos",
  "Los Laureles",
  "Los Molinos",
  "Los Muchachos - La Alborada",
  "Los Nogales",
  "Los Quirquinchos",
  "Los Zapallos",
  "Lucio V. López",
  "Luis Palacios",
  "Maciel",
  "Maggiolo",
  "Malabrigo",
  "Marcelino Escalada",
  "Margarita",
  "María Juana",
  "María Luisa",
  "María Susana",
  "María Teresa",
  "Matilde",
  "Máximo Paz",
  "Melincué",
  "Miguel Torres",
  "Moisés Ville",
  "Monigotes",
  "Monje",
  "Monte Flores",
  "Monte Vera",
  "Montefiore",
  "Montes de Oca",
  "Murphy",
  "Naré",
  "Nelson",
  "Nueva Lehmann",
  "Nuevo Torino",
  "Ñanducita",
  "Oliveros",
  "Palacios",
  "Paraje 29",
  "Paraje Chaco Chico",
  "Paraje La Costa",
  "Paraje San Manuel",
  "Pavón",
  "Pavón Arriba",
  "Pedro Gómez Cello",
  "Pérez",
  "Peyrano",
  "Piamonte",
  "Pilar",
  "Piñero",
  "Plaza Clucellas",
  "Plaza Matilde",
  "Plaza Saguier",
  "Pozo Borrado",
  "Pozo de los Indios",
  "Presidente Roca",
  "Progreso",
  "Providencia",
  "Pueblo Andino",
  "Pueblo Esther",
  "Pueblo Marini",
  "Pueblo Muñóz",
  "Pueblo Santa Lucía",
  "Pueblo Uranga",
  "Puerto Aragón",
  "Puerto Arroyo Seco",
  "Puerto General San Martín",
  "Puerto Reconquista",
  "Pujato",
  "Rafaela",
  "Ramayón",
  "Ramona",
  "Reconquista",
  "Recreo",
  "Ricardone",
  "Rincón Norte",
  "Rincón Potrero",
  "Roldán",
  "Romang",
  "Rosario",
  "Rueda",
  "Rufino",
  "Sa Pereyra",
  "Saladero Mariano Cabal",
  "Salto Grande",
  "San Agustín",
  "San Antonio",
  "San Antonio de Obligado",
  "San Bernardo",
  "San Carlos Centro",
  "San Carlos Norte",
  "San Carlos Sud",
  "San Cristóbal",
  "San Eduardo",
  "San Eugenio",
  "San Fabián",
  "San Francisco de Santa Fe",
  "San Genaro",
  "San Genaro Norte",
  "San Gregorio",
  "San Guillermo",
  "San Javier",
  "San Jerónimo del Sauce",
  "San Jerónimo Norte",
  "San Jerónimo Sud",
  "San Jorge",
  "San José de la Esquina",
  "San José del Rincón",
  "San Justo",
  "San Lorenzo",
  "San Mariano",
  "San Martín de las Escobas",
  "San Martín Norte",
  "San Vicente",
  "Sancti Spiritu",
  "Sanford",
  "Santa Clara de Buena Vista",
  "Santa Clara de Saguier",
  "Santa Fe",
  "Santa Isabel",
  "Santa Margarita",
  "Santa Rosa de Calchines",
  "Santa Teresa",
  "Santo Domingo",
  "Santo Tomé",
  "Santurce",
  "Sargento Cabral",
  "Sarmiento",
  "Sastre",
  "Sauce Viejo",
  "Serodino",
  "Silva",
  "Soldini",
  "Soledad",
  "Stephenson",
  "Suardi",
  "Sunchales",
  "Susana",
  "Tacuarendí",
  "Tacural",
  "Tartagal",
  "Teodelina",
  "Theobald",
  "Timbúes",
  "Toba",
  "Tortugas",
  "Tostado",
  "Totoras",
  "Traill",
  "Venado Tuerto",
  "Vera",
  "Vera y Pintado",
  "Videla",
  "Vila",
  "Villa Adelina",
  "Villa Amelia",
  "Villa Ana",
  "Villa Cañás",
  "Villa Constitución",
  "Villa del Plata",
  "Villa Eloísa",
  "Villa Elvira",
  "Villa Gobernador Gálvez",
  "Villa Guillermina",
  "Villa Josefina",
  "Villa La Rivera (Oliveros)",
  "Villa La Rivera (Pueblo Andino)",
  "Villa Laura",
  "Villa Minetti",
  "Villa Mugueta",
  "Villa Ocampo",
  "Villa San José",
  "Villa Saralegui",
  "Villa Trinidad",
  "Villada",
  "Virginia",
  "Wheelwright",
  "Wildermuth",
  "Zavalla",
  "Zenón Pereyra",
];

const DIACRITICS = new RegExp("[\\u0300-\\u036f]", "g");

export function normalizeLocalidad(value: string) {
  return value.normalize("NFD").replace(DIACRITICS, "").toLowerCase().trim();
}

const NORMALIZED_SET = new Set(SANTA_FE_LOCALIDADES.map(normalizeLocalidad));

export function isValidLocalidad(value: string) {
  return NORMALIZED_SET.has(normalizeLocalidad(value));
}

export function matchLocalidades(query: string, limit = 8) {
  const q = normalizeLocalidad(query);
  if (!q) return [];

  const scored: { loc: string; score: number }[] = [];
  for (const loc of SANTA_FE_LOCALIDADES) {
    const n = normalizeLocalidad(loc);
    let score: number;
    if (n === q) score = 0;
    else if (n.startsWith(q)) score = 1;
    else if (n.includes(q)) score = 2;
    else continue;
    scored.push({ loc, score });
  }

  scored.sort((a, b) => a.score - b.score || a.loc.localeCompare(b.loc, "es"));
  return scored.slice(0, limit).map((s) => s.loc);
}
